name: docker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: jhunufernandes/python-github-actions/.github/workflows/lint.yml@main
    with:
      python_version: "3.14"
      install_args: "-e .[dev]"
  build:
    if: github.event_name == 'push'
    needs:
      - lint
    uses: jhunufernandes/python-github-actions/.github/workflows/docker.yml@main
