name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-venv:
    uses: jhunufernandes/python-github-actions/.github/workflows/deps.yml@main
    with:
      extras: tests
      python_version: "3.14"
  run-tests:
    needs:
      - build-venv
    uses: jhunufernandes/python-github-actions/.github/workflows/tests.yml@main
    with:
      extras: tests
